### ISSUE TITLE
tox support

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy-bench#2]
It would be nice to be able to run all benchmarks on all supported scrapy and python versions with a single ``tox`` command. ``tox`` also supports passing arguments via it's ``posargs`` feature, that could allow to run e.g. a single benchmark on all versions, or set number of runs.

**Comment by Parth-Vader** [comment]
Tox support added via latest commit.

**Comment by lopuhin** [comment]
Here is the commit for the reference: 42bd30d95417859bb98f97f870be86b9cf34f4e0. Nice job on it @Parth-Vader !
