### ISSUE TITLE
Add more benchmarker for the project

### ISSUE THREAD

**Issue by nctl144** [scrapy/scrapy-bench#21]
What do you guys think if we add more benchmarkers to this project, which can be helpful for those performance label issues listed in Scrapy repo right now? In addition, it might be more convenient for the GSoC project Improve Scrapy Performance.
For example, for the issue scrapy/scrapy#3125, we can add the benchmarker for the ItemLoader, and we might add more benchmarkers for urlparse too. 
In addition, I think adding the vmprof profiling command to the command line tool of this project might also be a good idea? It just makes things so much easier.
What do you think?

**Comment by lopuhin** [comment]
@nctl144 both adding convenient vmprof support and more diverse benchmarks are definitely good ideas!

**Comment by Parth-Vader** [comment]
@nctl144 You can have a look at [this](https://github.com/scrapy/scrapy/issues/2792) issue I had created.

**Comment by nctl144** [comment]
@lopuhin great! I will create some PRs for that soon!
@Parth-Vader yeah Ive read through that and I thought it's a good idea to create it in this project instead since scrapy-bench is mainly for profiling :)

**Comment by Parth-Vader** [comment]
@nctl144 Can this be closed? I see you've addressed both the issues.

**Comment by nctl144** [comment]
Yeah definitely!
