### ISSUE TITLE
Allow to customise the root URL for the books spider benchmark

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy-bench#8]
It's not super important, but right now the URL http://localhost/books.toscrape.com/index.html is hardcoded. It would be nice to be able to run benchmark against a different URL: for example, it might be hosted on a different machine, or the user might not have admin rights required to listen on port 80. In my case, nginx installed by homebrew on OS X is listening on port 8080 by default, so for me it's easier to just point the spider at a different address.

**Comment by nctl144** [comment]
I noticed that too when I tried scrapy-bench on my Mac, so can you suggest a solution to this @lopuhin? I think adding an url option to the command line would be convenient.

**Comment by lopuhin** [comment]
Fixed in #16
