### ISSUE TITLE
Simplify nginx install step in the docs

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy-bench#9]
Need to double-check, but I think it would be enough to just install nginx using the default package manager, and put downloaded site to nginx content root, without the firewall setup and custom config. Also would be nice to provide examples for common Linux distros and OS X (``brew install nginx``, ``cp books.toscrape.com /usr/local/var/www/``, ``nginx``).

**Comment by Parth-Vader** [comment]
I agree that the firewall setup etc. isn't required for it. It worked for me by just putting the site to the root folder.
